---
- name: Install ZSH and dependencies
  apt:
    name:
      - zsh
      - fonts-powerline
    state: present
    update_cache: yes

- name: Set ZSH as default shell
  ansible.builtin.command:
    cmd: chsh -s $(which zsh)
  changed_when: false
  register: zsh_shell_change
  when: zsh_default_shell

- name: Install Oh My Zsh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install-oh-my-zsh.sh
    mode: '0755'
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: Run Oh My Zsh installer
  ansible.builtin.command:
    cmd: /tmp/install-oh-my-zsh.sh --unattended
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
  environment:
    RUNZSH: "no"

- name: Install ZSH plugins
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/{{ item.name }}"
  loop:
    - { name: zsh-syntax-highlighting, repo: https://github.com/zsh-users/zsh-syntax-highlighting }
    - { name: zsh-autosuggestions, repo: https://github.com/zsh-users/zsh-autosuggestions }

- name: Configure .zshrc
  ansible.builtin.template:
    src: zshrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  notify: Show restart message
